d = [{'product_name':'картошка фри', 'price':45},
{'product_name':'бургер', 'price':135},
{'product_name':'пицца', 'price':95},
{'product_name':'кола', 'price':39},
{'product_name':'спрайт', 'price':39},
{'product_name':'фанта', 'price':39},
{'product_name':'яблочный сок', 'price':20},
{'product_name':'вишньовый сок', 'price':20},
{'product_name':'сок мултифрукт', 'price':20},
{'product_name':'йогурт', 'price':45},
{'product_name':'тортик', 'price':45},
{'product_name':'морожено', 'price':15}] 