dict = [{'product_name':'картопля фрі', 'price':45},
{'product_name':'бургер', 'price':135},
{'product_name':'піцца', 'price':95},
{'product_name':'кола', 'price':39},
{'product_name':'спрайт', 'price':39},
{'product_name':'фанта', 'price':39},
{'product_name':'яблуневий сік', 'price':20},
{'product_name':'вишневий сік', 'price':20},
{'product_name':'сік мултифрукт', 'price':20},
{'product_name':'йогурт', 'price':45},
{'product_name':'тортик', 'price':45},
{'product_name':'морозиво', 'price':15}] 