d = {'product_name':'french fries', 'price':45},
{'product_name':'burg', 'price':135},
{'product_name':'pizza', 'price':95},
{'product_name':'cola', 'price':29},
{'product_name':'fanta', 'price':39},
{'product_name':'sprite', 'price':39},
{'product_name':'apple juice', 'price':20},
{'product_name':'cherry juice', 'price':20},
{'product_name':'multifruit juice', 'price':20},
{'product_name':'yogurt', 'price':45},
{'product_name':'cake', 'price':45},
{'product_name':'ice cream', 'price':15}